<?php

namespace Pg\GsbFraisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisForfaitRepository extends EntityRepository
{
}
